name: Pipeline
on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  build:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn
      - uses: s0/git-publish-subdir-action@develop
        name: To Hostinger
        env:
          REPO: self
          BRANCH: build # The branch name where you want to push the assets
          FOLDER: build # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          # SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          MESSAGE: "Build: ({sha}) {msg}" # The commit message


  # upload-to-s3-new-design:
  #   if: github.ref == 'refs/heads/new-design'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: yarn
  #     - run: yarn build
  #     - uses: shallwefootball/s3-upload-action@master
  #       name: Upload S3
  #       id: S3
  #       with:
  #         aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
  #         aws_bucket: "test-frontend-bae"
  #         source_dir: "./build"
  #         destination_dir: ""
